### ISSUE TITLE
CRITICAL: TypeError: unorderable types: Page() < Page()

### ISSUE THREAD

**Issue by codito** [pR0Ps/pelican-subtle#23]
See this error message on running `pelican -D` with pelican-subtle theme.

~~~
$ pelican -D
...
Error stack:
CRITICAL: TypeError: unorderable types: Page() < Page()
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\external\bb\codito.in\env\Scripts\pelican.exe\__main__.py", line 9, in <module>
  File "E:\external\bb\codito.in\env\lib\site-packages\pelican\__init__.py", line 478, in main
    pelican.run()
  File "E:\external\bb\codito.in\env\lib\site-packages\pelican\__init__.py", line 183, in run
    p.generate_output(writer)
  File "E:\external\bb\codito.in\env\lib\site-packages\pelican\generators.py", line 587, in generate_output
    self.generate_pages(writer)
  File "E:\external\bb\codito.in\env\lib\site-packages\pelican\generators.py", line 486, in generate_pages
    self.generate_articles(write)
  File "E:\external\bb\codito.in\env\lib\site-packages\pelican\generators.py", line 364, in generate_articles
    blog=True)
  File "E:\external\bb\codito.in\env\lib\site-packages\pelican\writers.py", line 211, in write_file
    override_output)
  File "E:\external\bb\codito.in\env\lib\site-packages\pelican\writers.py", line 155, in _write_file
    output = template.render(localcontext)
  File "E:\external\bb\codito.in\env\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "E:\external\bb\codito.in\env\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\external\bb\codito.in\env\lib\site-packages\jinja2\_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "E:\external\bb\codito.in\themes\pelican-subtle\templates\article.html", line 1, in <module>
    {% extends "base.html" %}
  File "E:\external\bb\codito.in\themes\pelican-subtle\templates\base.html", line 119, in <module>
    {% block header %}
  File "E:\external\bb\codito.in\themes\pelican-subtle\templates\base.html", line 123, in <module>
    {% for p in pages|sort %}
  File "E:\external\bb\codito.in\env\lib\site-packages\jinja2\filters.py", line 265, in do_sort
    return sorted(value, key=sort_func, reverse=reverse)
TypeError: unorderable types: Page() < Page()
~~~

**Comment by codito** [comment]
Workaround below. If this is the right fix, I will create a patch.

~~~diff
diff --git a/templates/base.html b/templates/base.html
index 8e30b5d..369c988 100644
--- a/templates/base.html
+++ b/templates/base.html
@@ -120,7 +120,7 @@
       <p id="header">
       <a href="{{ SITEURL }}">Home</a>

-      {% for p in pages|sort %}
+      {% for p in pages%}
       {% if p.url != "index.html" %}
       &#124; <a href="{{ SITEURL }}/{{ p.url }}">{{ p.title }}</a>
       {% endif %}
~~~

**Comment by pR0Ps** [comment]
Yep, this is the right fix. The theme should respect the ordering of the ['PAGE_ORDER_BY' setting](https://github.com/getpelican/pelican/blob/master/docs/settings.rst#ordering-content).

**Comment by codito** [comment]
@pR0Ps sure, sent a PR your way :)
