### ISSUE TITLE
Update for Pelican 3.7

### ISSUE THREAD

**Issue by fxer** [pR0Ps/pelican-subtle#33]
I took a swing at it myself but couldn't figure it out straight away, at the very least the JINJA_EXTENSIONS list has been replaced with the dict [JINJA_ENVIRONMENT](http://docs.getpelican.com/en/stable/settings.html?highlight=jinja_environment) which is used in `plugins/assets/assets.py`. I tried replacing the line:

`    pelican.settings['JINJA_EXTENSIONS'].append(AssetsExtension)`

with: 

`    pelican.settings['JINJA_ENVIRONMENT'][AssetsExtension] = True`

but that leads to a different error:

> CRITICAL: AttributeError: 'list' object has no attribute 'setdefault'
Traceback (most recent call last):
  File "/Users/jmontgomery/.virtualenvs/blog/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/Users/jmontgomery/.virtualenvs/blog/lib/python3.6/site-packages/pelican/__init__.py", line 394, in main
    readers = Readers(settings)
  File "/Users/jmontgomery/.virtualenvs/blog/lib/python3.6/site-packages/pelican/readers.py", line 471, in __init__
    self.readers[fmt] = reader_class(self.settings)
  File "/Users/jmontgomery/.virtualenvs/blog/lib/python3.6/site-packages/pelican/readers.py", line 250, in __init__
    settings.setdefault('extension_configs', {})
AttributeError: 'list' object has no attribute 'setdefault'

I could do some more digging unless you've got an idea what's going on, thanks Carey!

**Comment by pR0Ps** [comment]
Thanks for pointing this out @fxer, it should be fixed now. Let me know if you see anything else!
